//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MokaCms.DataAccessFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public int UserId { get; set; }
        public string GivenNames { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
